### ISSUE TITLE
Position check in single h1 assessment creates problem with other systems than Wordpress 

### ISSUE THREAD

**Issue by Sebobo** [Yoast/javascript#873] opened 2020-09-30 13:46 UTC
The check in https://github.com/Yoast/javascript/blob/3ed64a9f2b676221687a4fbb72c9d403d94d4e35/packages/yoastseo/src/assessments/seo/SingleH1Assessment.js#L69 always fails in integrations for WYSIWYG CMS that have the page markup included in the content.
There is usually a div or something else between the content start and the h1.

See https://github.com/Yoast/Yoast-SEO-for-Neos/issues/57

It would be helpful if this can be turned off or somehow be configurable to allow a custom check that fits to the CMS.

**Comment by Djennez** [comment] 2020-09-30 13:58
Closing as a duplicate of https://github.com/Yoast/wordpress-seo/issues/15301

**Closed by Djennez** 2020-09-30 13:58 UTC
