### ISSUE TITLE
Creating the web worker fails on relative URLs

### ISSUE THREAD

**Issue by hansjovis** [Yoast/javascript#418] opened 2019-12-09 09:46 UTC
## Explanation
When a website uses relative URLs to point to assets, e.g. `/worker-script.js`, creating the web worker fails and the SEO- and Readability Analysis cannot be run.

## Technical details
When creating the web worker we check whether the URL to the worker script
(e.g. `https://example.org/worker-script.js` when calling:
```js
const webworker = new Worker( 'https://example.org/worker-script.js' );
```
) has the same origin as the current website (e.g. `https://some-other-website.org`).

We check this by casting both the website as well as the path to the worker to `URL` objects and checking their host names.

This fails when a website uses relative URLs, e.g. `/worker-script.js`, instead of the above absolute URLs. Since a relative URL cannot be cast to `URL` objects:
```js
// This fails:
const url = new URL( '/worker-script.js' );
```

## Solution
The same origin check is done here:

https://github.com/Yoast/javascript/blob/7bbe79da581e30d88e8b38eb63fa6bb01745c81a/packages/yoastseo/src/worker/createWorker.js#L39-L46

We need to check whether `urlA` or `urlB` are relative URLs and, if so, return `true`. Relative URLs are relative to the current origin, so are necessarily from the same origin.

**Comment by Djennez** [comment] 2019-12-10 15:28
So I have seen different reports coming in about the metabox not able to load. Problem is that FireFox and Chrome throw different errors in the console to I couldn't pinpoint these issues. 

FireFox errors:
- TypeError: /wp-content/plugins/wordpress-seo/js/dist/wp-seo-analysis-worker-1270.min.js is not a valid URL.
- TypeError: a is null

Chrome errors:
- Uncaught TypeError: Failed to construct 'URL': Invalid URL
- Uncaught TypeError: Cannot set property 'innerHTML' of null

The cause of these errors seems to be in [this commit](https://github.com/Yoast/javascript/commit/09d98e27b4da9dc118cd7c5415de6f24363ae88e) which was milestoned for 12.6 (around when the issues started coming in). 

If a website is (wrongly) configured with a relative URL for the `WP_CONTENT_URL` like this:
`define('WP_CONTENT_URL', '/wp-content');`
you will start to see the above mentioned errors in the console. Looking at the support forums and GitHub issues, there seem plenty of sites what are configured like this.

**Comment by FPCSJames** [comment] 2019-12-10 19:09
This error also occurs on sites with non-relative URLs set in `WP_CONTENT_URL`. One of my affected sites has:

`define( 'WP_CONTENT_URL', 'https://www.example.org/assets' );`

This is valid, but the issue persists.

**Comment by jdevalk** [comment] 2019-12-11 10:34
@FPCSJames thanks for your feedback!

>  In the case of this site, the theme JS was overriding URL, which prevents usage of new URL().

We're not going to solve that, that's just horrible non-prefixing code on the theme's part.

> The URL constructor accepts a base as its second param.

That's good to know and might actually help fix this :)

**Comment by igorschoester** [comment] 2019-12-11 13:39
Closed via https://github.com/Yoast/javascript/pull/422

**Closed by igorschoester** 2019-12-11 13:39 UTC
Labels: bug

**Comment by FPCSJames** [comment] 2019-12-11 17:23
> We're not going to solve that, that's just horrible non-prefixing code on the theme's part.

@jdevalk I agree, terrible code in the theme and entirely on them to solve. The worst part - it doesn't even appear they were using what they set up. Stupid.
